name: apexcardio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  flutter_blue_plus: ^2.3.11
  permission_handler: ^11.3.1
  sqflite: ^2.4.3
  path: ^1.9.1
  file_selector: ^1.1.0
  share_plus: ^13.3.0
  path_provider: ^2.1.6
  pdf: ^3.12.0
  printing: ^5.14.3
  flutter_foreground_task: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: "assets/icons/apexcardio_light.png"

  image_path_ios: "assets/icons/apexcardio_light.png"
  image_path_ios_dark_transparent: "assets/icons/apexcardio_dark.png"
  image_path_ios_tinted_grayscale: "assets/icons/apexcardio_tinted.png"

  desaturate_tinted_to_grayscale_ios: false
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 500