import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String currentLang = "EN";

  LanguageProvider() {
    loadFromLocal();
  }

  static const List<String> supportedLanguages = [
    "EN",
    "RO",
    "DE",
    "RU",
    "ES",
  ];

  Future<void> loadFromLocal() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString("language") ?? "EN";
    currentLang = supportedLanguages.contains(saved) ? saved : "EN";
    notifyListeners();
  }

  final Map<String, Map<String, String>> dictionary = {
    "EN": {
      "live_tab": "Live",
      "recordings_tab": "Recordings",
      "settings_tab": "Settings",
      "dark_mode": "Dark Mode",
      "show_grid_title": "Show Grid",
      "language_title": "App Language",
      "font_scale_title": "Font Scale",
      "font_scale_title_small": "Small",
      "font_scale_title_normal": "Normal",
      "font_scale_title_big": "Big",
      "ble_connected": "Device Connected",
      "ble_disconnected": "Device Disconnected",
      "press_to_scan": "Press to scan",
      "ble_search": "Search",
      "available_devices": "Available Devices",
      "ble_connect_to_device": "Connect",
      "succes_connect": "Successfully connected!",
      "error_connect": "Connection error!",
      "no_device": "No devices :(",
      "no_device_connected": "No Device Connected",
      "unknown_device": "Unknown Device",
      "heart_rate": "Heart rate",
      "respiration": "Respiration",
      "appearance_section": "Appearance",
      "language_text_section": "Language & text",
      "scan_again": "Scan again",
      "stop_scan": "Stop scan",
      "disconnect": "Disconnect",
      "saved_recordings": "Saved recordings",
      "create_recording": "Create recording",
      "recording_active": "Recording active",
      "starting": "Starting...",
      "open": "Open",
      "preparing_storage": "Preparing recording storage...",
      "recording_storage_error": "Recording storage error",
      "unknown_error": "Unknown error",
      "dismiss": "Dismiss",
      "device_connected": "Device connected",
      "signal_gap": "Signal gap",
      "paused": "Paused",
      "waiting_for_device": "Waiting for device",
      "recording": "Recording",
      "saved": "Saved",
      "pending": "{count} pending",
      "retry_save": "Retry save",
      "resume": "Resume",
      "pause": "Pause",
      "saving": "Saving...",
      "stop": "Stop",
      "no_recordings_yet": "No recordings yet",
      "no_recordings_description": "Create a recording and it will appear here automatically.",
      "could_not_load_recordings": "Could not load recordings",
      "retry": "Retry",
      "reset": "Reset",
      "samples_label": "Samples",
      "measured_label": "Measured",
      "delete": "Delete",
      "recording_options": "Recording options",
      "measured": "{duration} measured",
      "completed": "Completed",
      "interrupted": "Interrupted",
      "recording_name": "Recording name",
      "notes": "Notes",
      "optional": "Optional",
      "cancel": "Cancel",
      "start_recording": "Start recording",
      "recording_started": "Recording started",
      "could_not_start_recording": "Could not start recording: {error}",
      "could_not_pause_recording": "Could not pause recording: {error}",
      "could_not_resume_recording": "Could not resume recording: {error}",
      "stop_recording_question": "Stop recording?",
      "stop_recording_description": "The recording will be finalized and saved on this device.",
      "recording_saved": "Recording saved",
      "could_not_stop_recording": "Could not stop recording: {error}",
      "pending_data_saved": "Pending data saved",
      "write_retry_failed": "Write retry failed: {error}",
      "could_not_import_recording": "Could not import recording: {error}",
      "stop_before_delete": "Stop the active recording before deleting it.",
      "delete_recording_question": "Delete recording?",
      "delete_recording_description": "\"{name}\" and all of its stored signal data will be permanently deleted.",
      "recording_deleted": "Recording deleted",
      "could_not_delete_recording": "Could not delete recording: {error}",
      "recording_not_found": "Recording not found",
      "edit": "Edit",
      "more": "More",
      "signal_viewer": "Signal viewer",
      "visible": "{seconds} s visible",
      "samples": "{count} samples",
      "interval": "Interval",
      "change": "Change",
      "choose_interval": "Choose interval",
      "recording_length": "Recording length: {duration}",
      "max_graph_interval": "Max graph interval: 20 s",
      "start": "Start",
      "end": "End",
      "show_interval": "Show interval",
      "end_after_start": "End must be after start.",
      "end_outside_recording": "End is outside the recording.",
      "interval_too_long": "A graph interval can be at most 20 seconds.",
      "gaps_visible_range": "Gaps in visible range",
      "gap": "Gap",
      "average": "Average",
      "rr_interval": "R-R interval",
      "breath_interval": "Breath interval",
      "sample_rate": "Sample rate",
      "signal_coverage": "Signal coverage",
      "timeline": "Timeline",
      "started": "Started",
      "status": "Status",
      "device": "Device",
      "technical_details": "Technical details",
      "rate_disclaimer": "Rate values are signal-derived estimates and are not a medical diagnosis.",
      "recording_actions": "Recording actions",
      "generate_share_pdf": "Generate / Share PDF",
      "print_pdf": "Print PDF",
      "export_apex": "Export ApexCardio file (.apex)",
      "export_csv": "Export CSV",
      "pdf_ready": "PDF report ready",
      "print_opened": "Print dialog opened",
      "apex_export_ready": "ApexCardio export ready",
      "csv_export_ready": "CSV export ready",
      "action_failed": "Action failed: {error}",
      "edit_recording": "Edit recording",
      "save": "Save",
      "day_short": "d",
      "hour_short": "h",
      "minute_short": "min",
      "second_short": "s",
      "display": "Display",
      "language": "Language",
      "text_size": "Text size",
      "connected_device": "Connected device",
      "device_required_recording": "Connect the ApexCardio device before starting a recording.",
      "stop_recording_to_connect": "Stop the active recording before connecting to another device.",
      "select_start_end": "Select start time",
      "ecg_details": "Detailed ECG",
      "respiration_details": "Detailed Respiration",
      "signal_range": "Signal range",
      "signal_mean": "Signal mean",
      "signal_rms": "Signal RMS",
      "excerpt": "Excerpt",
      "time": "Time",
      "analysis_note": "Signal-derived values are estimates for review and are not a medical diagnosis.",
      "device_behavior": "Device behavior",
      "auto_reconnect": "Auto reconnect",
      "auto_reconnect_desc": "Reconnect automatically after an unexpected signal loss.",
      "apex_only": "Show only ApexCardio",
      "apex_only_desc": "Hide unrelated Bluetooth devices while scanning.",

      "ui_section": "Interface",
      "recording_indicator": "Recording indicator",
      "recording_indicator_desc": "Show the recording dot in the app bar.",
      "recording_indicator_animation": "Animate recording indicator",
      "recording_indicator_animation_desc": "Pulse the recording dot while data is being captured.",
      "compact_recordings": "Compact recording list",
      "compact_recordings_desc": "Use tighter spacing when many recordings are stored.",

    },
    "RO": {
      "live_tab": "Live",
      "recordings_tab": "Înregistrări",
      "settings_tab": "Setări",
      "dark_mode": "Mod întunecat",
      "show_grid_title": "Arată grila",
      "language_title": "Limba aplicației",
      "font_scale_title": "Mărimea textului",
      "font_scale_title_small": "Mic",
      "font_scale_title_normal": "Normal",
      "font_scale_title_big": "Mare",
      "ble_connected": "Dispozitiv conectat",
      "ble_disconnected": "Dispozitiv deconectat",
      "press_to_scan": "Apasă pentru scanare",
      "ble_search": "Caută",
      "available_devices": "Dispozitive disponibile",
      "ble_connect_to_device": "Conectează",
      "succes_connect": "Conectat cu succes!",
      "error_connect": "Eroare la conectare!",
      "no_device": "Niciun dispozitiv :(",
      "no_device_connected": "Niciun dispozitiv conectat",
      "unknown_device": "Dispozitiv necunoscut",
      "heart_rate": "Ritm cardiac",
      "respiration": "Respirație",
      "appearance_section": "Aspect",
      "language_text_section": "Limbă și text",
      "scan_again": "Scanează din nou",
      "stop_scan": "Oprește scanarea",
      "disconnect": "Deconectează",
      "saved_recordings": "Înregistrări salvate",
      "create_recording": "Creează înregistrare",
      "recording_active": "Înregistrare activă",
      "starting": "Se pornește...",
      "open": "Deschide",
      "preparing_storage": "Se pregătește stocarea...",
      "recording_storage_error": "Eroare de stocare",
      "unknown_error": "Eroare necunoscută",
      "dismiss": "Închide",
      "device_connected": "Dispozitiv conectat",
      "signal_gap": "Întrerupere semnal",
      "paused": "Pauză",
      "waiting_for_device": "Se așteaptă dispozitivul",
      "recording": "Înregistrare",
      "saved": "Salvat",
      "pending": "{count} în așteptare",
      "retry_save": "Reîncearcă salvarea",
      "resume": "Continuă",
      "pause": "Pauză",
      "saving": "Se salvează...",
      "stop": "Oprește",
      "no_recordings_yet": "Nicio înregistrare",
      "no_recordings_description": "Creează o înregistrare și va apărea automat aici.",
      "could_not_load_recordings": "Înregistrările nu au putut fi încărcate",
      "retry": "Reîncearcă",
      "reset": "Reset",
      "samples_label": "Mostre",
      "measured_label": "Măsurat",
      "delete": "Șterge",
      "recording_options": "Opțiuni înregistrare",
      "measured": "{duration} măsurat",
      "completed": "Finalizată",
      "interrupted": "Întreruptă",
      "recording_name": "Numele înregistrării",
      "notes": "Notițe",
      "optional": "Opțional",
      "cancel": "Anulează",
      "start_recording": "Pornește",
      "recording_started": "Înregistrarea a pornit",
      "could_not_start_recording": "Înregistrarea nu a putut porni: {error}",
      "could_not_pause_recording": "Pauza nu a putut fi activată: {error}",
      "could_not_resume_recording": "Înregistrarea nu a putut continua: {error}",
      "stop_recording_question": "Oprești înregistrarea?",
      "stop_recording_description": "Înregistrarea va fi finalizată și salvată pe acest dispozitiv.",
      "recording_saved": "Înregistrare salvată",
      "could_not_stop_recording": "Înregistrarea nu a putut fi oprită: {error}",
      "pending_data_saved": "Datele în așteptare au fost salvate",
      "write_retry_failed": "Reîncercarea salvării a eșuat: {error}",
      "could_not_import_recording": "Importul a eșuat: {error}",
      "stop_before_delete": "Oprește înregistrarea activă înainte de ștergere.",
      "delete_recording_question": "Ștergi înregistrarea?",
      "delete_recording_description": "\"{name}\" și toate datele de semnal vor fi șterse permanent.",
      "recording_deleted": "Înregistrare ștearsă",
      "could_not_delete_recording": "Înregistrarea nu a putut fi ștearsă: {error}",
      "recording_not_found": "Înregistrarea nu a fost găsită",
      "edit": "Editează",
      "more": "Mai mult",
      "signal_viewer": "Vizualizare semnal",
      "visible": "{seconds} s vizibile",
      "samples": "{count} mostre",
      "interval": "Interval",
      "change": "Schimbă",
      "choose_interval": "Alege intervalul",
      "recording_length": "Durata înregistrării: {duration}",
      "max_graph_interval": "Interval maxim pe grafic: 20 s",
      "start": "Start",
      "end": "Sfârșit",
      "show_interval": "Arată intervalul",
      "end_after_start": "Sfârșitul trebuie să fie după start.",
      "end_outside_recording": "Sfârșitul depășește înregistrarea.",
      "interval_too_long": "Intervalul graficului poate avea maximum 20 de secunde.",
      "gaps_visible_range": "Întreruperi în intervalul vizibil",
      "gap": "Întrerupere",
      "average": "Medie",
      "rr_interval": "Interval R-R",
      "breath_interval": "Interval respirator",
      "sample_rate": "Rată eșantionare",
      "signal_coverage": "Acoperire semnal",
      "timeline": "Cronologie",
      "started": "Pornită",
      "status": "Stare",
      "device": "Dispozitiv",
      "technical_details": "Detalii tehnice",
      "rate_disclaimer": "Valorile de ritm sunt estimate din semnal și nu reprezintă un diagnostic medical.",
      "recording_actions": "Acțiuni înregistrare",
      "generate_share_pdf": "Generează / distribuie PDF",
      "print_pdf": "Printează PDF",
      "export_apex": "Exportă fișier ApexCardio (.apex)",
      "export_csv": "Exportă CSV",
      "pdf_ready": "Raport PDF pregătit",
      "print_opened": "Dialogul de printare a fost deschis",
      "apex_export_ready": "Export ApexCardio pregătit",
      "csv_export_ready": "Export CSV pregătit",
      "action_failed": "Acțiunea a eșuat: {error}",
      "edit_recording": "Editează înregistrarea",
      "save": "Salvează",
      "day_short": "z",
      "hour_short": "h",
      "minute_short": "min",
      "second_short": "s",
      "display": "Afișare",
      "language": "Limbă",
      "text_size": "Mărime text",
      "connected_device": "Dispozitiv conectat",
      "device_required_recording": "Conectează dispozitivul ApexCardio înainte de a porni o înregistrare.",
      "stop_recording_to_connect": "Oprește înregistrarea activă înainte de a conecta alt dispozitiv.",
      "select_start_end": "Alege momentul de început",
      "ecg_details": "ECG detaliat",
      "respiration_details": "Respirație detaliată",
      "signal_range": "Amplitudine semnal",
      "signal_mean": "Media semnalului",
      "signal_rms": "RMS semnal",
      "excerpt": "Secvență",
      "time": "Timp",
      "analysis_note": "Valorile derivate din semnal sunt estimări pentru analiză și nu reprezintă un diagnostic medical.",
      "device_behavior": "Comportament dispozitiv",
      "auto_reconnect": "Reconectare automată",
      "auto_reconnect_desc": "Reconectează automat după o pierdere neașteptată a semnalului.",
      "apex_only": "Arată doar ApexCardio",
      "apex_only_desc": "Ascunde alte dispozitive Bluetooth în timpul scanării.",

      "ui_section": "Interfață",
      "recording_indicator": "Indicator de înregistrare",
      "recording_indicator_desc": "Arată bulina de înregistrare în bara de sus.",
      "recording_indicator_animation": "Animează indicatorul",
      "recording_indicator_animation_desc": "Bulina pulsează cât timp se înregistrează date.",
      "compact_recordings": "Listă compactă de înregistrări",
      "compact_recordings_desc": "Folosește spațiere mai mică atunci când ai multe înregistrări.",

    },
    "DE": {
      "live_tab": "Live",
      "recordings_tab": "Aufnahmen",
      "settings_tab": "Einstellungen",
      "dark_mode": "Dunkelmodus",
      "show_grid_title": "Raster anzeigen",
      "language_title": "App-Sprache",
      "font_scale_title": "Textgröße",
      "font_scale_title_small": "Klein",
      "font_scale_title_normal": "Normal",
      "font_scale_title_big": "Groß",
      "ble_connected": "Gerät verbunden",
      "ble_disconnected": "Gerät getrennt",
      "press_to_scan": "Zum Scannen drücken",
      "ble_search": "Suchen",
      "available_devices": "Verfügbare Geräte",
      "ble_connect_to_device": "Verbinden",
      "succes_connect": "Erfolgreich verbunden!",
      "error_connect": "Verbindungsfehler!",
      "no_device": "Keine Geräte :(",
      "no_device_connected": "Kein Gerät verbunden",
      "unknown_device": "Unbekanntes Gerät",
      "heart_rate": "Herzfrequenz",
      "respiration": "Atmung",
      "appearance_section": "Darstellung",
      "language_text_section": "Sprache & Text",
      "scan_again": "Erneut scannen",
      "stop_scan": "Scan stoppen",
      "disconnect": "Trennen",
      "saved_recordings": "Gespeicherte Aufnahmen",
      "create_recording": "Aufnahme erstellen",
      "recording_active": "Aufnahme aktiv",
      "starting": "Wird gestartet...",
      "open": "Öffnen",
      "preparing_storage": "Speicher wird vorbereitet...",
      "recording_storage_error": "Speicherfehler",
      "unknown_error": "Unbekannter Fehler",
      "dismiss": "Schließen",
      "device_connected": "Gerät verbunden",
      "signal_gap": "Signallücke",
      "paused": "Pausiert",
      "waiting_for_device": "Warte auf Gerät",
      "recording": "Aufnahme",
      "saved": "Gespeichert",
      "pending": "{count} ausstehend",
      "retry_save": "Speichern wiederholen",
      "resume": "Fortsetzen",
      "pause": "Pause",
      "saving": "Speichern...",
      "stop": "Stoppen",
      "no_recordings_yet": "Noch keine Aufnahmen",
      "no_recordings_description": "Erstelle eine Aufnahme; sie erscheint automatisch hier.",
      "could_not_load_recordings": "Aufnahmen konnten nicht geladen werden",
      "retry": "Wiederholen",
      "reset": "Zurücksetzen",
      "samples_label": "Samples",
      "measured_label": "Gemessen",
      "delete": "Löschen",
      "recording_options": "Aufnahmeoptionen",
      "measured": "{duration} gemessen",
      "completed": "Abgeschlossen",
      "interrupted": "Unterbrochen",
      "recording_name": "Aufnahmename",
      "notes": "Notizen",
      "optional": "Optional",
      "cancel": "Abbrechen",
      "start_recording": "Aufnahme starten",
      "recording_started": "Aufnahme gestartet",
      "could_not_start_recording": "Aufnahme konnte nicht gestartet werden: {error}",
      "could_not_pause_recording": "Aufnahme konnte nicht pausiert werden: {error}",
      "could_not_resume_recording": "Aufnahme konnte nicht fortgesetzt werden: {error}",
      "stop_recording_question": "Aufnahme stoppen?",
      "stop_recording_description": "Die Aufnahme wird abgeschlossen und auf diesem Gerät gespeichert.",
      "recording_saved": "Aufnahme gespeichert",
      "could_not_stop_recording": "Aufnahme konnte nicht gestoppt werden: {error}",
      "pending_data_saved": "Ausstehende Daten gespeichert",
      "write_retry_failed": "Speichern fehlgeschlagen: {error}",
      "could_not_import_recording": "Import fehlgeschlagen: {error}",
      "stop_before_delete": "Stoppe die aktive Aufnahme vor dem Löschen.",
      "delete_recording_question": "Aufnahme löschen?",
      "delete_recording_description": "\"{name}\" und alle Signaldaten werden dauerhaft gelöscht.",
      "recording_deleted": "Aufnahme gelöscht",
      "could_not_delete_recording": "Aufnahme konnte nicht gelöscht werden: {error}",
      "recording_not_found": "Aufnahme nicht gefunden",
      "edit": "Bearbeiten",
      "more": "Mehr",
      "signal_viewer": "Signalanzeige",
      "visible": "{seconds} s sichtbar",
      "samples": "{count} Samples",
      "interval": "Intervall",
      "change": "Ändern",
      "choose_interval": "Intervall wählen",
      "recording_length": "Aufnahmelänge: {duration}",
      "max_graph_interval": "Max. Graphintervall: 20 s",
      "start": "Start",
      "end": "Ende",
      "show_interval": "Intervall anzeigen",
      "end_after_start": "Das Ende muss nach dem Start liegen.",
      "end_outside_recording": "Das Ende liegt außerhalb der Aufnahme.",
      "interval_too_long": "Ein Graphintervall darf höchstens 20 Sekunden lang sein.",
      "gaps_visible_range": "Lücken im sichtbaren Bereich",
      "gap": "Lücke",
      "average": "Durchschnitt",
      "rr_interval": "R-R-Intervall",
      "breath_interval": "Atemintervall",
      "sample_rate": "Abtastrate",
      "signal_coverage": "Signalabdeckung",
      "timeline": "Zeitleiste",
      "started": "Gestartet",
      "status": "Status",
      "device": "Gerät",
      "technical_details": "Technische Details",
      "rate_disclaimer": "Die Ratenwerte werden aus dem Signal geschätzt und sind keine medizinische Diagnose.",
      "recording_actions": "Aufnahmeaktionen",
      "generate_share_pdf": "PDF erstellen / teilen",
      "print_pdf": "PDF drucken",
      "export_apex": "ApexCardio-Datei exportieren (.apex)",
      "export_csv": "CSV exportieren",
      "pdf_ready": "PDF-Bericht bereit",
      "print_opened": "Druckdialog geöffnet",
      "apex_export_ready": "ApexCardio-Export bereit",
      "csv_export_ready": "CSV-Export bereit",
      "action_failed": "Aktion fehlgeschlagen: {error}",
      "edit_recording": "Aufnahme bearbeiten",
      "save": "Speichern",
      "day_short": "T",
      "hour_short": "Std",
      "minute_short": "Min",
      "second_short": "Sek",
      "display": "Anzeige",
      "language": "Sprache",
      "text_size": "Textgröße",
      "connected_device": "Verbundenes Gerät",
      "device_required_recording": "Verbinde das ApexCardio-Gerät, bevor du eine Aufnahme startest.",
      "stop_recording_to_connect": "Stoppe die aktive Aufnahme, bevor du ein anderes Gerät verbindest.",
      "select_start_end": "Startzeit wählen",
      "ecg_details": "Detailliertes EKG",
      "respiration_details": "Detaillierte Atmung",
      "signal_range": "Signalbereich",
      "signal_mean": "Signalmittelwert",
      "signal_rms": "Signal-RMS",
      "excerpt": "Ausschnitt",
      "time": "Zeit",
      "analysis_note": "Aus dem Signal abgeleitete Werte sind Schätzungen zur Überprüfung und keine medizinische Diagnose.",
      "device_behavior": "Geräteverhalten",
      "auto_reconnect": "Automatisch verbinden",
      "auto_reconnect_desc": "Nach einem unerwarteten Signalverlust automatisch neu verbinden.",
      "apex_only": "Nur ApexCardio anzeigen",
      "apex_only_desc": "Andere Bluetooth-Geräte beim Scannen ausblenden.",

      "ui_section": "Oberfläche",
      "recording_indicator": "Aufnahmeanzeige",
      "recording_indicator_desc": "Zeigt den Aufnahmepunkt in der oberen Leiste.",
      "recording_indicator_animation": "Aufnahmeanzeige animieren",
      "recording_indicator_animation_desc": "Der Punkt pulsiert während der Aufnahme.",
      "compact_recordings": "Kompakte Aufnahmeliste",
      "compact_recordings_desc": "Engere Abstände bei vielen gespeicherten Aufnahmen.",

    },
    "RU": {
      "live_tab": "Live",
      "recordings_tab": "Записи",
      "settings_tab": "Настройки",
      "dark_mode": "Тёмная тема",
      "show_grid_title": "Показывать сетку",
      "language_title": "Язык приложения",
      "font_scale_title": "Размер текста",
      "font_scale_title_small": "Малый",
      "font_scale_title_normal": "Обычный",
      "font_scale_title_big": "Большой",
      "ble_connected": "Устройство подключено",
      "ble_disconnected": "Устройство отключено",
      "press_to_scan": "Нажмите для поиска",
      "ble_search": "Поиск",
      "available_devices": "Доступные устройства",
      "ble_connect_to_device": "Подключить",
      "succes_connect": "Успешно подключено!",
      "error_connect": "Ошибка подключения!",
      "no_device": "Нет устройств :(",
      "no_device_connected": "Устройство не подключено",
      "unknown_device": "Неизвестное устройство",
      "heart_rate": "Пульс",
      "respiration": "Дыхание",
      "appearance_section": "Оформление",
      "language_text_section": "Язык и текст",
      "scan_again": "Искать снова",
      "stop_scan": "Остановить поиск",
      "disconnect": "Отключить",
      "saved_recordings": "Сохранённые записи",
      "create_recording": "Создать запись",
      "recording_active": "Запись активна",
      "starting": "Запуск...",
      "open": "Открыть",
      "preparing_storage": "Подготовка хранилища...",
      "recording_storage_error": "Ошибка хранилища",
      "unknown_error": "Неизвестная ошибка",
      "dismiss": "Закрыть",
      "device_connected": "Устройство подключено",
      "signal_gap": "Разрыв сигнала",
      "paused": "Пауза",
      "waiting_for_device": "Ожидание устройства",
      "recording": "Запись",
      "saved": "Сохранено",
      "pending": "Ожидает: {count}",
      "retry_save": "Повторить сохранение",
      "resume": "Продолжить",
      "pause": "Пауза",
      "saving": "Сохранение...",
      "stop": "Стоп",
      "no_recordings_yet": "Записей пока нет",
      "no_recordings_description": "Создайте запись, и она автоматически появится здесь.",
      "could_not_load_recordings": "Не удалось загрузить записи",
      "retry": "Повторить",
      "reset": "Сбросить",
      "samples_label": "Сэмплы",
      "measured_label": "Измерено",
      "delete": "Удалить",
      "recording_options": "Параметры записи",
      "measured": "измерено {duration}",
      "completed": "Завершено",
      "interrupted": "Прервано",
      "recording_name": "Название записи",
      "notes": "Заметки",
      "optional": "Необязательно",
      "cancel": "Отмена",
      "start_recording": "Начать запись",
      "recording_started": "Запись началась",
      "could_not_start_recording": "Не удалось начать запись: {error}",
      "could_not_pause_recording": "Не удалось поставить на паузу: {error}",
      "could_not_resume_recording": "Не удалось продолжить запись: {error}",
      "stop_recording_question": "Остановить запись?",
      "stop_recording_description": "Запись будет завершена и сохранена на этом устройстве.",
      "recording_saved": "Запись сохранена",
      "could_not_stop_recording": "Не удалось остановить запись: {error}",
      "pending_data_saved": "Ожидающие данные сохранены",
      "write_retry_failed": "Повторное сохранение не удалось: {error}",
      "could_not_import_recording": "Не удалось импортировать запись: {error}",
      "stop_before_delete": "Остановите активную запись перед удалением.",
      "delete_recording_question": "Удалить запись?",
      "delete_recording_description": "\"{name}\" и все данные сигнала будут удалены навсегда.",
      "recording_deleted": "Запись удалена",
      "could_not_delete_recording": "Не удалось удалить запись: {error}",
      "recording_not_found": "Запись не найдена",
      "edit": "Изменить",
      "more": "Ещё",
      "signal_viewer": "Просмотр сигнала",
      "visible": "видно {seconds} с",
      "samples": "сэмплов: {count}",
      "interval": "Интервал",
      "change": "Изменить",
      "choose_interval": "Выбрать интервал",
      "recording_length": "Длина записи: {duration}",
      "max_graph_interval": "Макс. интервал графика: 20 с",
      "start": "Начало",
      "end": "Конец",
      "show_interval": "Показать интервал",
      "end_after_start": "Конец должен быть после начала.",
      "end_outside_recording": "Конец находится за пределами записи.",
      "interval_too_long": "Интервал графика не может превышать 20 секунд.",
      "gaps_visible_range": "Разрывы в видимом интервале",
      "gap": "Разрыв",
      "average": "Среднее",
      "rr_interval": "Интервал R-R",
      "breath_interval": "Интервал дыхания",
      "sample_rate": "Частота дискретизации",
      "signal_coverage": "Покрытие сигнала",
      "timeline": "Шкала времени",
      "started": "Начало",
      "status": "Статус",
      "device": "Устройство",
      "technical_details": "Технические данные",
      "rate_disclaimer": "Значения частоты оцениваются по сигналу и не являются медицинским диагнозом.",
      "recording_actions": "Действия с записью",
      "generate_share_pdf": "Создать / поделиться PDF",
      "print_pdf": "Печать PDF",
      "export_apex": "Экспорт файла ApexCardio (.apex)",
      "export_csv": "Экспорт CSV",
      "pdf_ready": "PDF-отчёт готов",
      "print_opened": "Диалог печати открыт",
      "apex_export_ready": "Экспорт ApexCardio готов",
      "csv_export_ready": "Экспорт CSV готов",
      "action_failed": "Ошибка действия: {error}",
      "edit_recording": "Изменить запись",
      "save": "Сохранить",
      "day_short": "д",
      "hour_short": "ч",
      "minute_short": "мин",
      "second_short": "с",
      "display": "Экран",
      "language": "Язык",
      "text_size": "Размер текста",
      "connected_device": "Подключённое устройство",
      "device_required_recording": "Подключите устройство ApexCardio перед началом записи.",
      "stop_recording_to_connect": "Остановите активную запись перед подключением другого устройства.",
      "select_start_end": "Выберите время начала",
      "ecg_details": "Подробный ЭКГ",
      "respiration_details": "Подробное дыхание",
      "signal_range": "Диапазон сигнала",
      "signal_mean": "Среднее сигнала",
      "signal_rms": "RMS сигнала",
      "excerpt": "Фрагмент",
      "time": "Время",
      "analysis_note": "Значения, полученные из сигнала, являются оценочными и не являются медицинским диагнозом.",
      "device_behavior": "Поведение устройства",
      "auto_reconnect": "Автоподключение",
      "auto_reconnect_desc": "Автоматически подключаться после неожиданной потери сигнала.",
      "apex_only": "Только ApexCardio",
      "apex_only_desc": "Скрывать другие Bluetooth-устройства при поиске.",

      "ui_section": "Интерфейс",
      "recording_indicator": "Индикатор записи",
      "recording_indicator_desc": "Показывать точку записи в верхней панели.",
      "recording_indicator_animation": "Анимация индикатора",
      "recording_indicator_animation_desc": "Точка пульсирует во время записи данных.",
      "compact_recordings": "Компактный список записей",
      "compact_recordings_desc": "Уменьшить интервалы при большом количестве записей.",

    },
    "ES": {
      "live_tab": "Live",
      "recordings_tab": "Grabaciones",
      "settings_tab": "Ajustes",
      "dark_mode": "Modo oscuro",
      "show_grid_title": "Mostrar cuadrícula",
      "language_title": "Idioma de la app",
      "font_scale_title": "Tamaño del texto",
      "font_scale_title_small": "Pequeño",
      "font_scale_title_normal": "Normal",
      "font_scale_title_big": "Grande",
      "ble_connected": "Dispositivo conectado",
      "ble_disconnected": "Dispositivo desconectado",
      "press_to_scan": "Pulsa para buscar",
      "ble_search": "Buscar",
      "available_devices": "Dispositivos disponibles",
      "ble_connect_to_device": "Conectar",
      "succes_connect": "¡Conectado correctamente!",
      "error_connect": "¡Error de conexión!",
      "no_device": "No hay dispositivos :(",
      "no_device_connected": "Ningún dispositivo conectado",
      "unknown_device": "Dispositivo desconocido",
      "heart_rate": "Frecuencia cardíaca",
      "respiration": "Respiración",
      "appearance_section": "Apariencia",
      "language_text_section": "Idioma y texto",
      "scan_again": "Buscar de nuevo",
      "stop_scan": "Detener búsqueda",
      "disconnect": "Desconectar",
      "saved_recordings": "Grabaciones guardadas",
      "create_recording": "Crear grabación",
      "recording_active": "Grabación activa",
      "starting": "Iniciando...",
      "open": "Abrir",
      "preparing_storage": "Preparando almacenamiento...",
      "recording_storage_error": "Error de almacenamiento",
      "unknown_error": "Error desconocido",
      "dismiss": "Cerrar",
      "device_connected": "Dispositivo conectado",
      "signal_gap": "Interrupción de señal",
      "paused": "Pausada",
      "waiting_for_device": "Esperando dispositivo",
      "recording": "Grabando",
      "saved": "Guardado",
      "pending": "{count} pendientes",
      "retry_save": "Reintentar guardado",
      "resume": "Continuar",
      "pause": "Pausa",
      "saving": "Guardando...",
      "stop": "Detener",
      "no_recordings_yet": "Aún no hay grabaciones",
      "no_recordings_description": "Crea una grabación y aparecerá aquí automáticamente.",
      "could_not_load_recordings": "No se pudieron cargar las grabaciones",
      "retry": "Reintentar",
      "reset": "Restablecer",
      "samples_label": "Muestras",
      "measured_label": "Medido",
      "delete": "Eliminar",
      "recording_options": "Opciones de grabación",
      "measured": "{duration} medidos",
      "completed": "Completada",
      "interrupted": "Interrumpida",
      "recording_name": "Nombre de la grabación",
      "notes": "Notas",
      "optional": "Opcional",
      "cancel": "Cancelar",
      "start_recording": "Iniciar grabación",
      "recording_started": "Grabación iniciada",
      "could_not_start_recording": "No se pudo iniciar la grabación: {error}",
      "could_not_pause_recording": "No se pudo pausar la grabación: {error}",
      "could_not_resume_recording": "No se pudo continuar la grabación: {error}",
      "stop_recording_question": "¿Detener la grabación?",
      "stop_recording_description": "La grabación se finalizará y se guardará en este dispositivo.",
      "recording_saved": "Grabación guardada",
      "could_not_stop_recording": "No se pudo detener la grabación: {error}",
      "pending_data_saved": "Datos pendientes guardados",
      "write_retry_failed": "Falló el reintento de guardado: {error}",
      "could_not_import_recording": "No se pudo importar la grabación: {error}",
      "stop_before_delete": "Detén la grabación activa antes de eliminarla.",
      "delete_recording_question": "¿Eliminar grabación?",
      "delete_recording_description": "\"{name}\" y todos sus datos de señal se eliminarán permanentemente.",
      "recording_deleted": "Grabación eliminada",
      "could_not_delete_recording": "No se pudo eliminar la grabación: {error}",
      "recording_not_found": "Grabación no encontrada",
      "edit": "Editar",
      "more": "Más",
      "signal_viewer": "Visor de señal",
      "visible": "{seconds} s visibles",
      "samples": "{count} muestras",
      "interval": "Intervalo",
      "change": "Cambiar",
      "choose_interval": "Elegir intervalo",
      "recording_length": "Duración de la grabación: {duration}",
      "max_graph_interval": "Intervalo máx. del gráfico: 20 s",
      "start": "Inicio",
      "end": "Fin",
      "show_interval": "Mostrar intervalo",
      "end_after_start": "El final debe estar después del inicio.",
      "end_outside_recording": "El final está fuera de la grabación.",
      "interval_too_long": "El intervalo del gráfico puede ser de hasta 20 segundos.",
      "gaps_visible_range": "Interrupciones en el intervalo visible",
      "gap": "Interrupción",
      "average": "Promedio",
      "rr_interval": "Intervalo R-R",
      "breath_interval": "Intervalo respiratorio",
      "sample_rate": "Frecuencia de muestreo",
      "signal_coverage": "Cobertura de señal",
      "timeline": "Cronología",
      "started": "Inicio",
      "status": "Estado",
      "device": "Dispositivo",
      "technical_details": "Detalles técnicos",
      "rate_disclaimer": "Los valores de frecuencia se estiman a partir de la señal y no son un diagnóstico médico.",
      "recording_actions": "Acciones de grabación",
      "generate_share_pdf": "Generar / compartir PDF",
      "print_pdf": "Imprimir PDF",
      "export_apex": "Exportar archivo ApexCardio (.apex)",
      "export_csv": "Exportar CSV",
      "pdf_ready": "Informe PDF listo",
      "print_opened": "Diálogo de impresión abierto",
      "apex_export_ready": "Exportación ApexCardio lista",
      "csv_export_ready": "Exportación CSV lista",
      "action_failed": "La acción falló: {error}",
      "edit_recording": "Editar grabación",
      "save": "Guardar",
      "day_short": "d",
      "hour_short": "h",
      "minute_short": "min",
      "second_short": "s",
      "display": "Pantalla",
      "language": "Idioma",
      "text_size": "Tamaño del texto",
      "connected_device": "Dispositivo conectado",
      "device_required_recording": "Conecta el dispositivo ApexCardio antes de iniciar una grabación.",
      "stop_recording_to_connect": "Detén la grabación activa antes de conectar otro dispositivo.",
      "select_start_end": "Seleccionar hora de inicio",
      "ecg_details": "ECG detallado",
      "respiration_details": "Respiración detallada",
      "signal_range": "Rango de señal",
      "signal_mean": "Media de señal",
      "signal_rms": "RMS de señal",
      "excerpt": "Fragmento",
      "time": "Hora",
      "analysis_note": "Los valores derivados de la señal son estimaciones para revisión y no constituyen un diagnóstico médico.",
      "device_behavior": "Comportamiento del dispositivo",
      "auto_reconnect": "Reconexión automática",
      "auto_reconnect_desc": "Reconectar automáticamente tras una pérdida inesperada de señal.",
      "apex_only": "Mostrar solo ApexCardio",
      "apex_only_desc": "Ocultar otros dispositivos Bluetooth durante la búsqueda.",

      "ui_section": "Interfaz",
      "recording_indicator": "Indicador de grabación",
      "recording_indicator_desc": "Mostrar el punto de grabación en la barra superior.",
      "recording_indicator_animation": "Animar indicador de grabación",
      "recording_indicator_animation_desc": "El punto pulsa mientras se capturan datos.",
      "compact_recordings": "Lista compacta de grabaciones",
      "compact_recordings_desc": "Usar menos espacio cuando hay muchas grabaciones.",

    },
  };

  String translate(
    String key, [
    Map<String, Object?> values = const <String, Object?>{},
  ]) {
    var value =
        dictionary[currentLang]?[key] ??
        dictionary["EN"]?[key] ??
        key;

    for (final entry in values.entries) {
      value = value.replaceAll(
        '{${entry.key}}',
        '${entry.value}',
      );
    }

    return value;
  }

  Future<void> setLanguage(String langCode) async {
    if (!supportedLanguages.contains(langCode)) {
      return;
    }

    currentLang = langCode;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString("language", langCode);
  }
}
